# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 8c3c7a73ab27e1283493c7196a3a84d652f94dd421408231585d9de59ec960442a5a1affd278c1b28fa55a8f88df947ddd74bad28ec5ac65e8973291322bb449

test:
  secret_key_base: 56dd1e48b22e14daf6cfd88408fb84ca40a47a4afea3647997d2b9625dd56ef87f7b3981120de2b2c39610d42d38ad4f7755b2413658d21e96ecc655b93ac1c4

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
